### ISSUE TITLE
Missing Type: `ISerpGoogleOrganicTaskPostRequestInfo`

### ISSUE THREAD

**Issue by BenJackGill** [dataforseo/TypeScriptClient#4]
We have an interface for Google Local Finder Task POST Requests under `ISerpGoogleLocalFinderTaskPostRequestInfo` but the `organic` version is missing.

Interface type of `ISerpGoogleOrganicTaskPostRequestInfo` needs to be added.

We can still use `ISerpTaskRequestInfo` but that would be less specific than the expected `ISerpGoogleOrganicTaskPostRequestInfo` version.

**Comment by lVics** [comment]
Organic endpoint like in some other endpoints (where used ISerpTaskRequestInfo) have the same structure (unlike ISerpGoogleLocalFinderTaskPostRequestInfo) so we grouped them in 1 request item. There is no reason to duplicate request objects with the same request body
